name: Build and Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: ğŸš€ Build, Copy Assets, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: ğŸ“¦ Install dependencies
        run: |
          rm -rf node_modules && npm install

      - name: ğŸ› ï¸ Build application
        run: |
          npm run build

      - name: ğŸ“‚ Copy assets to dist
        run: |
          cp -r ./src ./dist/src

      - name: ğŸš€ Deploy dist via SFTP
        uses: appleboy/scp-action@v0.2.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: "./dist/"
          target: "/public_html/"
